Repository Arquisoft/dede_en1b, pull requests merged in 2022-04, with the labels that each got.

#103 Updated Documentation for V2 of the System
  docs/03_system_scope_and_context.adoc
  docs/04_solution_strategy.adoc
  docs/06_runtime_view.adoc
  docs/07_deployment_view.adoc
  docs/09_design_decisions.adoc
Labels: documentation

#134 Solid V3: Read/Write Addresses from POD
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.tsx
  webapp/src/components/checkout-shipping/Shipping.tsx
  webapp/src/components/user/AddressForm.tsx
  webapp/src/components/user/SOLIDLogin.tsx
  webapp/src/components/user/UserProfile.tsx
  webapp/src/components/user/address.tsx
  webapp/src/css/AddressForm.css
  webapp/src/css/Footer.css
  webapp/src/shared/shareddtypes.ts
Labels: SOLID

#142 Changed orderCards in Admin view and sorted reviews and orders
  restapi/package-lock.json
  webapp/package-lock.json
  webapp/src/components/administrator/AdminView.tsx
  webapp/src/components/administrator/OrderAdminCard.tsx
  webapp/src/components/administrator/OrderAdminDetails.tsx
  webapp/src/components/products/ProductPage.tsx
  webapp/src/components/user/UserProfile.tsx
Labels: creative

#143 Improved shipping view message
  webapp/src/components/user/address.tsx
Labels: enhancement, creative

#152 Final big merge from Develop into Production (master)
  webapp/src/App.tsx
  webapp/src/components/administrator/AdminView.tsx
  webapp/src/components/administrator/OrderAdminCard.tsx
  webapp/src/components/cart/CartItem.tsx
  webapp/src/components/cart/ShoppingCart.tsx
  webapp/src/components/checkout-shipping/Checkout.tsx
  webapp/src/components/checkout-shipping/CheckoutItem.tsx
  webapp/src/components/checkout-shipping/Shipping.tsx
  webapp/src/components/fragments/NavBar.tsx
  webapp/src/components/fragments/PageNotFound.tsx
  webapp/src/components/products/MainProducts.tsx
  webapp/src/components/products/ProductPage.tsx
  webapp/src/components/products/ReviewView.tsx
  webapp/src/components/products/ReviewsView.css
  webapp/src/components/products/image-gallery.scss
  webapp/src/components/user/AddressForm.tsx
  webapp/src/components/user/OrderCard.tsx
  webapp/src/components/user/OrderDetails.tsx
  webapp/src/components/user/UserProfile.tsx
  webapp/src/components/user/address.tsx
  webapp/src/css/CartItem.css
  webapp/src/css/CheckoutItem.css
  webapp/src/css/MainProducts.scss
  webapp/src/css/OrderCard.css
Labels: enhancement
